events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;

        location /user/ {
            set $upstream_user user-service;
            proxy_pass http://$upstream_user:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /consortium/ {
            set $upstream_consortium consortium-service;
            proxy_pass http://$upstream_consortium:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /email {
            set $upstream_email email-api;
            proxy_pass http://$upstream_email:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}